mp_cmediatheque:
    resource: "@MPCmediathequeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

HomeMpc:
    path:    /home
    defaults: { _controller: MPCmediathequeBundle:Advert:index}