mp_cmediatheque_auteurs:
    resource: "@MPCmediathequeBundle/Resources/config/routing/auteurs.xml"
    prefix:   /auteurs
    
mp_cmediatheque_homepage:
    path:     /
    defaults: { _controller: MPCmediathequeBundle:Default:index }
    
mp_cmediatheque_login:
    path:     /login
    defaults: { _controller: MPCmediathequeBundle:Default:login }

mp_cmediatheque_register:
    path:     /register
    defaults: { _controller: MPCmediathequeBundle:Default:register }

mp_cmediatheque_nouveaute:
    path:     /news
    defaults: { _controller: MPCmediathequeBundle:Default:nouveaute }
    
mp_cmediatheque_catalogue:
    path:    /catalogue/
    defaults: { _controller: MPCmediathequeBundle:Default:catalogue }
    
mpc_reservation:
    path:    /reservation
    defaults: { _controller: MPCmediathequeBundle:Default:reservation }

mpc_listeReservations:
    path:    /listResa
    defaults: { _controller: MPCmediathequeBundle:Default:listeResa }

mpc_userListeReservations:
    path:    /userListResa
    defaults: { _controller: MPCmediathequeBundle:Default:userListResa }

mpc_emprunt:
    path:    /emprunt
    defaults: { _controller: MPCmediathequeBundle:Default:emprunt }

mpc_listeEmprunt:
    path:    /listEmprunt
    defaults: { _controller: MPCmediathequeBundle:Default:listeEmprunt }

mpc_userListEmprunt:
    path:    /userListEmprunt
    defaults: { _controller: MPCmediathequeBundle:Default:userListEmprunt }

mpc_evenements:
    path:    /evenements
    defaults: { _controller: MPCmediathequeBundle:Default:showEvents }

mpc_retour:
    path:    /retour
    defaults: { _controller: MPCmediathequeBundle:Default:retour }