mp_cmediatheque_auteurs:
    resource: "@MPCmediathequeBundle/Resources/config/routing/auteurs.xml"
    prefix:   /auteurs
    
mp_cmediatheque_ouvrage:
    resource: "@MPCmediathequeBundle/Resources/config/routing/ouvrage.xml"
    prefix:   /catalogue

mp_cmediatheque_homepage:
    path:     /
    defaults: { _controller: MPCmediathequeBundle:Default:index }
