mpc_login:
    path:     /login
    defaults: { _controller: MPCmediathequeBundle:Default:login }

mpc_register:
    path:     /register
    defaults: { _controller: MPCmediathequeBundle:Default:register }
    
#####     Default      #####    

mpc_homepage:
    path:     /
    defaults: { _controller: MPCmediathequeBundle:Default:index }

mpc_nouveaute:
    path:     /news
    defaults: { _controller: MPCmediathequeBundle:Default:nouveaute }
    
mpc_catalogue:
    path:    /catalogue/
    defaults: { _controller: MPCmediathequeBundle:Default:catalogue }
    
#####     Reservation     ##### 

mpc_reservation:
    path:    /reservation
    defaults: { _controller: MPCmediathequeBundle:Reservation:reservation }

mpc_listeReservations:
    path:    /listResa
    defaults: { _controller: MPCmediathequeBundle:Reservation:listeResa }

mpc_userListeReservations:
    path:    /userListResa
    defaults: { _controller: MPCmediathequeBundle:Reservation:userListResa }
    
#####     Emprunt     #####

mpc_emprunt:
    path:    /emprunt
    defaults: { _controller: MPCmediathequeBundle:Emprunt:emprunt }

mpc_listeEmprunt:
    path:    /listEmprunt
    defaults: { _controller: MPCmediathequeBundle:Emprunt:listeEmprunt }

mpc_userListEmprunt:
    path:    /userListEmprunt
    defaults: { _controller: MPCmediathequeBundle:Emprunt:userListEmprunt }

mpc_retour:
    path:    /retour
    defaults: { _controller: MPCmediathequeBundle:Emprunt:retour }
    
#####     Evenements     #####

mpc_evenements:
    path:    /evenements
    defaults: { _controller: MPCmediathequeBundle:Event:showEvents }